Models/Empleado.cs
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace EXAMEN.Models
{
    public partial class Empleado
    {
        public Empleado()
        {
            Empleado_Habilidad = new HashSet<Empleado_Habilidad>();
            InverseIdJefeNavigation = new HashSet<Empleado>();
        }

        [Key]
        public int IdEmpleado { get; set; }
        [Required]
        [StringLength(100)]
        public string NombreCompleto { get; set; }
        [StringLength(50)]
        public string Cedula { get; set; }
        [StringLength(100)]
        [Required]
        [DataType(DataType.EmailAddress, ErrorMessage = "E-mail is not valid")]
        public string Correo { get; set; }
        [Column(TypeName = "date")]
        public DateTime? FechaNacimiento { get; set; }
        [Column(TypeName = "date")]
        public DateTime FechaIngreso { get; set; }
        public int? IdJefe { get; set; }
        public int IdArea { get; set; }
        public byte[] Foto { get; set; }

        [ForeignKey(nameof(IdArea))]
        [InverseProperty(nameof(Area.Empleado))]
        public virtual Area IdAreaNavigation { get; set; }
        [ForeignKey(nameof(IdJefe))]
        [InverseProperty(nameof(Empleado.InverseIdJefeNavigation))]
        public virtual Empleado IdJefeNavigation { get; set; }
        [InverseProperty("IdEmpleadoNavigation")]
        public virtual ICollection<Empleado_Habilidad> Empleado_Habilidad { get; set; }
        [InverseProperty(nameof(Empleado.IdJefeNavigation))]
        public virtual ICollection<Empleado> InverseIdJefeNavigation { get; set; }
    }
}

Controllers/Empleado_HabilidadController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EXAMEN.Data;
using EXAMEN.Models;

namespace EXAMEN.Controllers
{
    public class Empleado_HabilidadController : Controller
    {
        private readonly ExamenContext _context;

        public Empleado_HabilidadController(ExamenContext context)
        {
            _context = context;
        }

        // GET: Empleado_Habilidad
        public async Task<IActionResult> Index(int? id)
        {
            ViewData["IdEmpleado"] = await _context.Empleado.Where(x => x.IdEmpleado == id).FirstOrDefaultAsync();
            var examenContext = _context.Empleado_Habilidad.Where(x => x.IdEmpleado == id);
            return View(await examenContext.ToListAsync());
        }

        // GET: Empleado_Habilidad/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var empleado_Habilidad = await _context.Empleado_Habilidad
                .Include(e => e.IdEmpleadoNavigation)
                .FirstOrDefaultAsync(m => m.IdHabilidad == id);
            if (empleado_Habilidad == null)
            {
                return NotFound();
            }

            return View(empleado_Habilidad);
        }

        // GET: Empleado_Habilidad/Create
        public IActionResult Create(int id)
        {
            ViewData["IdEmpleado"] = _context.Empleado.Where(x => x.IdEmpleado == id).FirstOrDefault();
            return View();
        }

        // POST: Empleado_Habilidad/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdHabilidad,IdEmpleado,NombreHabilidad")] Empleado_Habilidad empleado_Habilidad)
        {
            if (ModelState.IsValid)
            {
                _context.Add(empleado_Habilidad);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index), new { id = empleado_Habilidad.IdEmpleado });
            }
            ViewData["IdEmpleado"] = await _context.Empleado.Where(x => x.IdEmpleado == empleado_Habilidad.IdEmpleado).FirstOrDefaultAsync();
            return View(empleado_Habilidad);
        }

        // GET: Empleado_Habilidad/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var empleado_Habilidad = await _context.Empleado_Habilidad.FindAsync(id);
            if (empleado_Habilidad == null)
            {
                return NotFound();
            }
            ViewData["IdEmpleado"] = await _context.Empleado.Where(x => x.IdEmpleado == empleado_Habilidad.IdEmpleado).FirstOrDefaultAsync();
            return View(empleado_Habilidad);
        }

        // POST: Empleado_Habilidad/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdHabilidad,IdEmpleado,NombreHabilidad")] Empleado_Habilidad empleado_Habilidad)
        {
            if (id != empleado_Habilidad.IdHabilidad)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(empleado_Habilidad);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!Empleado_HabilidadExists(empleado_Habilidad.IdHabilidad))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index), new { id = empleado_Habilidad.IdEmpleado });
            }
            ViewData["IdEmpleado"] = await _context.Empleado.Where(x => x.IdEmpleado == empleado_Habilidad.IdEmpleado).FirstOrDefaultAsync();
            return View(empleado_Habilidad);
        }

        // GET: Empleado_Habilidad/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var empleado_Habilidad = await _context.Empleado_Habilidad
                .Include(e => e.IdEmpleadoNavigation)
                .FirstOrDefaultAsync(m => m.IdHabilidad == id);
            if (empleado_Habilidad == null)
            {
                return NotFound();
            }

            return View(empleado_Habilidad);
        }

        // POST: Empleado_Habilidad/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var empleado_Habilidad = await _context.Empleado_Habilidad.FindAsync(id);
            _context.Empleado_Habilidad.Remove(empleado_Habilidad);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index), new { id = id });
        }

        private bool Empleado_HabilidadExists(int id)
        {
            return _context.Empleado_Habilidad.Any(e => e.IdHabilidad == id);
        }
    }
}

Controllers/EmpleadosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EXAMEN.Data;
using EXAMEN.Models;
using Microsoft.AspNetCore.Http;
using System.IO;

namespace EXAMEN.Controllers
{
    public class EmpleadosController : Controller
    {
        private readonly ExamenContext _context;

        public EmpleadosController(ExamenContext context)
        {
            _context = context;
        }

        // GET: Empleados
        public async Task<IActionResult> Index()
        {
            var examenContext = _context.Empleado.Include(e => e.IdAreaNavigation).Include(e => e.IdJefeNavigation);
            ViewData["IdArea"] = new SelectList(_context.Area, "IdArea", "Nombre");
            return View(await examenContext.ToListAsync());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Index(int idArea)
        {
            ViewData["IdArea"] = new SelectList(_context.Area, "IdArea", "Nombre");
           
            var result = await _context.Empleado.Include(e => e.IdAreaNavigation).Include(e => e.IdJefeNavigation).Where(x => x.IdArea == idArea).ToListAsync();

            return View(result);
        }

        // GET: Empleados/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var empleado = await _context.Empleado
                .Include(e => e.IdAreaNavigation)
                .Include(e => e.IdJefeNavigation)
                .FirstOrDefaultAsync(m => m.IdEmpleado == id);
            if (empleado == null)
            {
                return NotFound();
            }

            return View(empleado);
        }

        // GET: Empleados/Create
        public IActionResult Create()
        {
            ViewData["IdArea"] = new SelectList(_context.Area, "IdArea", "Nombre");
            ViewData["IdJefe"] = new SelectList(_context.Empleado, "IdEmpleado", "NombreCompleto");
            return View();
        }

        // POST: Empleados/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdEmpleado,NombreCompleto,Cedula,Correo,FechaNacimiento,FechaIngreso,IdJefe,IdArea,Foto")] Empleado empleado, IFormFile Foto)
        {
            if (ModelState.IsValid)
            {
                if (Foto != null)
                {
                    if (Foto.Length > 0)
                    {
                        using (var ms = new MemoryStream())
                        {
                            Foto.CopyTo(ms);
                            empleado.Foto = ms.ToArray();
                        }
                    }
                    else
                    {
                        empleado.Foto = new Byte[1];
                    }
                }
                else
                {
                    empleado.Foto = new Byte[1];
                }

                _context.Add(empleado);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdArea"] = new SelectList(_context.Area, "IdArea", "Nombre", empleado.IdArea);
            ViewData["IdJefe"] = new SelectList(_context.Empleado, "IdEmpleado", "NombreCompleto", empleado.IdJefe);
            return View(empleado);
        }

        // GET: Empleados/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var empleado = await _context.Empleado.FindAsync(id);
            if (empleado == null)
            {
                return NotFound();
            }
            ViewData["IdArea"] = new SelectList(_context.Area, "IdArea", "Nombre", empleado.IdArea);
            ViewData["IdJefe"] = new SelectList(_context.Empleado, "IdEmpleado", "NombreCompleto", empleado.IdJefe);
            return View(empleado);
        }

        // POST: Empleados/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdEmpleado,NombreCompleto,Cedula,Correo,FechaNacimiento,FechaIngreso,IdJefe,IdArea,Foto")] Empleado empleado, IFormFile Foto)
        {
            if (id != empleado.IdEmpleado)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (Foto != null)
                    {
                        if (Foto.Length > 0)
                        {
                            using (var ms = new MemoryStream())
                            {
                                Foto.CopyTo(ms);
                                empleado.Foto = ms.ToArray();
                            }
                        }
                        else
                        {
                            empleado.Foto = new Byte[1];
                        }
                    }
                    else
                    {
                        empleado.Foto = new Byte[1];
                    }

                    _context.Update(empleado);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EmpleadoExists(empleado.IdEmpleado))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdArea"] = new SelectList(_context.Area, "IdArea", "Nombre", empleado.IdArea);
            ViewData["IdJefe"] = new SelectList(_context.Empleado, "IdEmpleado", "NombreCompleto", empleado.IdJefe);
            return View(empleado);
        }

        // GET: Empleados/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var empleado = await _context.Empleado
                .Include(e => e.IdAreaNavigation)
                .Include(e => e.IdJefeNavigation)
                .FirstOrDefaultAsync(m => m.IdEmpleado == id);
            if (empleado == null)
            {
                return NotFound();
            }

            return View(empleado);
        }

        // POST: Empleados/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var empleado = await _context.Empleado.FindAsync(id);
            _context.Empleado.Remove(empleado);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EmpleadoExists(int id)
        {
            return _context.Empleado.Any(e => e.IdEmpleado == id);
        }

        public async Task<IActionResult> ArbolEmpleados()
        {
            var lstEmpleados = await _context.Empleado.ToListAsync();
            var jefes = lstEmpleados.Where(x => x.IdJefe == null).ToList();

            List<Empleado> list = new();

            foreach (var item in jefes)
            {
                list.AddRange(GetChild(lstEmpleados, item.IdEmpleado));
            }

            return View(list);
        }



        public List<Empleado> GetChild(List<Empleado> list, int id)
        {
            var locations = list.Where(x => x.IdJefe == id || x.IdEmpleado == id).ToList();

            var child = locations.AsEnumerable().Union(
                                        list.AsEnumerable().Where(x => x.IdJefe == id).SelectMany(y => GetChild(list, y.IdEmpleado))).ToList();

            child = child.Where(x => x.IdJefe == null).ToList();

            return child;
        }
    }
}

Views/Empleados/ArbolEmpleados.cshtml
@model List<EXAMEN.Models.Empleado>

@{
    ViewData["Title"] = "ArbolEmpleados";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h4>Arbol de empleados</h4>

<div>
    <div class="row">
        @await Html.PartialAsync("_EmpleadosPartial", Model)
    </div>
</div>

Views/Empleados/Create.cshtml
@model EXAMEN.Models.Empleado

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h4>Nuevo Empleado</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="NombreCompleto" class="control-label"></label>
                <input asp-for="NombreCompleto" class="form-control" />
                <span asp-validation-for="NombreCompleto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cedula" class="control-label"></label>
                <input asp-for="Cedula" class="form-control" />
                <span asp-validation-for="Cedula" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Correo" class="control-label"></label>
                <input asp-for="Correo" class="form-control" />
                <span asp-validation-for="Correo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaNacimiento" class="control-label"></label>
                <input asp-for="FechaNacimiento" class="form-control" />
                <span asp-validation-for="FechaNacimiento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaIngreso" class="control-label"></label>
                <input asp-for="FechaIngreso" class="form-control" />
                <span asp-validation-for="FechaIngreso" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdJefe" class="control-label"></label>
                <select asp-for="IdJefe" class="form-control" asp-items="ViewBag.IdJefe">
                    <option value="">N/A</option>
                </select>
            </div>
            <div class="form-group">
                <label asp-for="IdArea" class="control-label"></label>
                <select asp-for="IdArea" class ="form-control" asp-items="ViewBag.IdArea">
                    
                </select>
            </div>
            <div class="form-group">
                <label asp-for="Foto" class="control-label"></label>
                <input type="file" name="Foto" class="form-control" />
                @*<span asp-validation-for="Foto" class="text-danger"></span>*@
            </div>
            <div class="form-group">
                <input type="submit" value="Crear" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Volver al listado</a>
</div>

Views/Empleados/Delete.cshtml
@model EXAMEN.Models.Empleado

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>¿Seguro que quieres eliminar este registro?</h3>
<div>
    <h4>Empleado</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NombreCompleto)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NombreCompleto)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cedula)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cedula)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Correo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Correo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaNacimiento)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaNacimiento)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaIngreso)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaIngreso)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Foto)
        </dt>
        <dd class="col-sm-10">
            @*@Html.DisplayFor(model => model.Foto)*@
            <img width="200" class="img-responsive full-width" src="data:image/jpeg;base64,@Convert.ToBase64String(Model.Foto)" />
        </dd>
        <dt class = "col-sm-2">
            Area
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdAreaNavigation.Nombre)
        </dd class>
        <dt class = "col-sm-2">
            Jefe
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdJefeNavigation.NombreCompleto)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="IdEmpleado" />
        <input type="submit" value="Eliminar" class="btn btn-danger" /> |
        <a asp-action="Index">Volver al listado</a>
    </form>
</div>

Views/Empleados/Details.cshtml
@model EXAMEN.Models.Empleado

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div>
    @{ 
        EXAMEN.Clases.Metodos metodos = new();
    }
    <h4>Detalle Empleado</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.NombreCompleto)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.NombreCompleto)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Cedula)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Cedula)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Correo)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Correo)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FechaNacimiento)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FechaNacimiento)
        </dd>
        <dt class="col-sm-2">
            Edad
        </dt>
        <dd class="col-sm-10">
            @metodos.CalcularEdad((DateTime)Model.FechaNacimiento)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FechaIngreso)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FechaIngreso)
        </dd>

        <dt class="col-sm-2">
            Años Laborando
        </dt>
        <dd class="col-sm-10">
            @metodos.CalcularEdad((DateTime)Model.FechaIngreso)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Foto)
        </dt>
        <dd class="col-sm-10">
            @*@Html.DisplayFor(model => model.Foto)*@
            <img width="200" class="img-responsive full-width" src="data:image/jpeg;base64,@Convert.ToBase64String(Model.Foto)" />
        </dd>
        <dt class="col-sm-2">
            Area
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IdAreaNavigation.Nombre)
        </dd>
        <dt class="col-sm-2">
            Jefe:
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IdJefeNavigation.NombreCompleto)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.IdEmpleado">Editar</a> |
    <a asp-action="Index">Volver al listado</a>
</div>

Views/Empleados/Edit.cshtml
@model EXAMEN.Models.Empleado

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h4>Editar Empleado</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="IdEmpleado" />
            <div class="form-group">
                <label asp-for="NombreCompleto" class="control-label"></label>
                <input asp-for="NombreCompleto" class="form-control" />
                <span asp-validation-for="NombreCompleto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cedula" class="control-label"></label>
                <input asp-for="Cedula" class="form-control" />
                <span asp-validation-for="Cedula" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Correo" class="control-label"></label>
                <input asp-for="Correo" class="form-control" />
                <span asp-validation-for="Correo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaNacimiento" class="control-label"></label>
                <input asp-for="FechaNacimiento" class="form-control" />
                <span asp-validation-for="FechaNacimiento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaIngreso" class="control-label"></label>
                <input asp-for="FechaIngreso" class="form-control" />
                <span asp-validation-for="FechaIngreso" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdJefe" class="control-label"></label>
                <select asp-for="IdJefe" class="form-control" asp-items="ViewBag.IdJefe">
                    <option value="">N/A</option>
                </select>
                <span asp-validation-for="IdJefe" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdArea" class="control-label"></label>
                <select asp-for="IdArea" class="form-control" asp-items="ViewBag.IdArea"></select>
                <span asp-validation-for="IdArea" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Foto" class="control-label"></label>
                <br />
                <img width="200" class="img-responsive full-width" src="data:image/jpeg;base64,@Convert.ToBase64String(Model.Foto)" />
                <br />
                <input type="file" name="Foto" class="form-control" />
                @*<span asp-validation-for="Foto" class="text-danger"></span>*@
            </div>
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Volver al listado</a>
</div>

Views/Empleados/Index.cshtml
@model IEnumerable<EXAMEN.Models.Empleado>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Empleados</h1>

<p>
    <a class="btn btn-primary" asp-action="Create">Nuevo Empleado</a>
</p>
<br />
<div class="form-group">
    <form asp-action="Index">
        <label class="control-label">Seleccionar Area</label>
        <select name="idArea" class="form-control d-inline-block w-50" asp-items="ViewBag.IdArea">
            @*<option value="0">-- Mostrar Todos --</option>*@
        </select>
        <input type="submit" class="btn btn-outline-primary" value="Buscar" />
    </form>
</div>
<br />
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.NombreCompleto)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cedula)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Correo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaNacimiento)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaIngreso)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Foto)
            </th>
            <th>
                Area
            </th>
            <th>
                Jefe
            </th>
            <th>
                Accion
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.NombreCompleto)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Cedula)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Correo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FechaNacimiento)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FechaIngreso)
                </td>
                <td>
                    <img width="40" class="img-responsive full-width" src="data:image/jpeg;base64,@Convert.ToBase64String(item.Foto)" />
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IdAreaNavigation.Nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IdJefeNavigation.NombreCompleto)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.IdEmpleado">Editar</a> |
                    <a asp-action="Details" asp-route-id="@item.IdEmpleado">Detalle</a> |
                    <a asp-action="Delete" asp-route-id="@item.IdEmpleado">Eliminar</a>
                </td>
            </tr>
        }
    </tbody>
</table>

Views/Empleados/_EmpleadosPartial.cshtml
@model List<EXAMEN.Models.Empleado>

<ul>
    @foreach (var item in Model)
    {
    <li>
        @if (item.InverseIdJefeNavigation.Count > 0)
        {
            <a asp-controller="Empleado_Habilidad" asp-action="Index" asp-route-id="@item.IdEmpleado">@item.NombreCompleto</a>
            @await Html.PartialAsync("_EmpleadosPartial", item.InverseIdJefeNavigation.ToList())
        }
        else
        {
            <a asp-controller="Empleado_Habilidad" asp-action="Index" asp-route-id="@item.IdEmpleado">@item.NombreCompleto</a>
        }
    </li>
    }
</ul>